#!/usr/bin/env sh

## bar on
#yabai -m config status_bar                   on
#yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
#yabai -m config status_bar_icon_font         "feather:Regular:12.0"
## yabai -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12"
#yabai -m config status_bar_background_color  0xff202020
#yabai -m config status_bar_foreground_color  0xffa8a8a8
## yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
## yabai -m config status_bar_space_icon_strip       VI VII VIII IX X
#yabai -m config status_bar_space_icon_strip       6 7 8 9 10
## yabai -m config status_bar_power_icon_strip   
#yabai -m config status_bar_power_icon_strip   
#yabai -m config status_bar_space_icon        
## yabai -m config status_bar_clock_icon        
#yabai -m config status_bar_clock_icon        


# bar off
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
lo

yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff505050
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

# ext monitor settings
# yabai -m config --space 2 top_padding	     160
echo "yabai configuration loaded.."

yabai -m rule --add app=Emacs manage=on
yabai -m rule --add app="^kitty$" manage=off
yabai -m rule --add app="^Emacs$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^cool-retro-term$" manage=off
yabai -m rule --add app="^GifCapture$" manage=off
yabai -m rule --add label="Firfox PIP3" app="^Firefox Developer Edition$" title="^(Picture-in-Picture)$" manage=off
yabai -m rule --add label="Firfox PIP2" app="Firefox Developer Edition" title="^(Picture-in-Picture)$" manage=off
yabai -m rule --add label="Firfox PIP" app="^Firefox$" title="^(Picture-in-Picture)$" manage=off
